version: '3'

services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=host.docker.internal
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=monitor_log_db
      - PG_PORT=5432
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

  redis:
    container_name: redis-db
    image: redis
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - backend_network
    volumes:
      - redis:/data

networks:
  backend_network:
    driver: bridge

volumes:
  redis:
    driver: local
